mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mapper/*Dao.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    date-format: yyyy年MM月dd日
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /img/**
  web:
    resources:
      static-locations: file:C:/resource/img
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  file:
    name: volunteer.log
